import { resolve } from "node:path";

export interface RelaySystemdOptions {
  workdir: string;
  config: string;
  deno: string;
  port: string;
  user: string;
  group: string;
}

if (import.meta.main) {
  const options = parseRelaySystemdArgs(Deno.args);
  console.log(renderRelaySystemdUnit(options));
}

export function renderRelaySystemdUnit(options: RelaySystemdOptions): string {
  return `# Generated by: deno task relay systemd
[Unit]
Description=TrendPublish Weixin Relay
Documentation=https://github.com/liyown/ai-trend-publish
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${options.workdir}
Environment=PORT=${options.port}
ExecStart=${options.deno} task relay --config ${options.config}
Restart=always
RestartSec=5
KillSignal=SIGINT
TimeoutStopSec=30
User=${options.user}
Group=${options.group}

[Install]
WantedBy=multi-user.target`;
}

export function parseRelaySystemdArgs(
  args: string[],
  defaults: Partial<RelaySystemdOptions> = {},
): RelaySystemdOptions {
  const cwd = resolve(Deno.cwd());
  const values = new Map<string, string>();

  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (!arg.startsWith("--")) continue;

    const [rawName, inlineValue] = arg.slice(2).split("=", 2);
    const name = rawName.trim();
    const value = inlineValue ?? args[index + 1];
    if (!value || value.startsWith("--")) {
      throw new Error(`参数 --${name} 需要提供值`);
    }
    values.set(name, value);
    if (inlineValue === undefined) index++;
  }

  const workdir = resolve(values.get("workdir") ?? defaults.workdir ?? cwd);
  const config = resolve(
    values.get("config") ?? defaults.config ??
      `${workdir}/config/trendpublish.config.ts`,
  );
  const deno = values.get("deno") ?? defaults.deno ?? Deno.execPath();
  const user = values.get("user") ?? defaults.user ?? "trendpublish";

  return {
    workdir,
    config,
    deno,
    port: values.get("port") ?? defaults.port ?? "8080",
    user,
    group: values.get("group") ??
      (values.has("user") ? user : defaults.group ?? user),
  };
}
